### ISSUE TITLE
Editing records

### ISSUE THREAD

**Issue by slyfox42** [mech/filemaker-ruby#16]
Hi, I'm having an issue updating records on Filemaker. This is my controller:

```ruby
# frozen_string_literal: true

# Api::V1::TechniciansController
module Api
  module V1
    class TechniciansController < Api::V1::BaseController
      before_action :authenticate!

      def show
        @technician = FM::Technician.equals(id: params[:id]).first
        render json: @technician, status: :ok
      end

      def update
        @technician = FM::Technician.equals(id: params[:id]).first
        @technician.auth_token = params[:authToken]
        @technician.save!
      end
    end
  end
end
```

and this is the model:

```ruby
# frozen_string_literal: true

module FM
  class Technician
    include Filemaker::Model

    database 'Interventi_Test'
    layout 'Tecnici Autorizzati'

    integer :id, fm_name: 'ID'
    string :name, fm_name: 'Nome'
    string :apple_id, fm_name: 'AppleId'
    string :auth_token, fm_name: 'AuthToken'

    def attributes
      ::TechnicianAttributes.perform(self)
    end

    def as_json(options = {})
      ::TechnicianAttributes.perform(self).as_json(options)
    end

    def to_json(options = {})
      ::TechnicianAttributes.perform(self).to_json(options)
    end
  end
end
```

I made sure that the user has full write and read access on the filemaker database, but for some reason when invoking the `save!` method, the changes aren't persisted to the database.

I can see the changes are made on the instance, and `save!` returns true, however I still see no changes on db.

Could you help me figure out what I'm missing?

Thanks

**Comment by mech** [comment]
See if you can give the field :id an identity like:

```ruby
integer :id, fm_name: 'ID', identity: true
```

The identity is a way to set up primary key and you can later use `find` to query without doing the dance of equal() or first():

```ruby
FM::Technician.find(params[:id])
```

Other than that it should be able to update if you have given write permission to XML web publishing.
