### ISSUE TITLE
`where` isn't properly searching records

### ISSUE THREAD

**Issue by corwinstephen** [mech/filemaker-ruby#5]
My member class includes `Filemaker::Model` and defines `string :email`, however:

`Member.where(email: 'email@example.com').count` returns 0 despite the fact that the email is verified in the db table. Running `member.not(email: 'email@example.com')` returns all records, including the one I'm looking for.

Searching instead for a member id (an integer field) works fine.

Thoughts?

**Comment by mech** [comment]
I have to check, but if you are using a-sign @, FileMaker is treating it differently as seen here http://help.filemaker.com/app/answers/detail/a_id/13715/~/refining-find-requests-in-filemaker-pro-using-find-operators

If you want, you can try it with non-email value like "name".

I could be wrong, will check after my work today.

**Comment by corwinstephen** [comment]
@mech you're exactly right. Thanks!

**Comment by mech** [comment]
I suffer from this issue also, if I recall correctly, I just replace it with a blank character like:

`Member.where(email: 'email example.com')`

**Comment by corwinstephen** [comment]
I just tried it. I was able to get the correct result with “email\@example.com <http://example.com/>”

**Comment by mech** [comment]
OOO.. that's even better! Tks for sharing!
