### ISSUE TITLE
Container url

### ISSUE THREAD

**Issue by alydersen** [mech/filemaker-ruby#9]
Hello,

First of all - thanks for you work on this great gem!

I need to get the URL of a container field, but can't find any functionality for it. Could this be added?

BR,
Andreas Lydersen

**Comment by mech** [comment]
Hi thanks for finding it useful. I believe you can get the URL as a string type. This is how I do it for container type:

```ruby
class Attachment
  include Filemaker::Model

  database 'MyDB'
  layout 'Attachment'

  # This is the container type URL being parse using URI.parse at
  # lib/filemaker/metadata/field.rb#L73
  string :attachment_url, fm_name: 'Attachment URL'
end
```

Do let me know if you can set it up :)

**Comment by alydersen** [comment]
Yes - my bad!

Do you have any functionality to get around the username/password dialog that is raised by the filmmaker server?

**Comment by mech** [comment]
You can download it using `Net::HTTP` with Basic Authentication:

```ruby
def download_protected_file
  req = Net::HTTP::Get.new(attachment_url)
  req.basic_auth(ENV['FILEMAKER_ACCOUNT_NAME'], ENV['FILEMAKER_PASSWORD'])
  res = Net::HTTP.new(ENV['FILEMAKER_HOST'], 80)
  res = res.start { |http| http.request(req) }
  
  res.body
end
```

**Comment by alydersen** [comment]
Thanks! Did the following for https compatibility:

`
    uri = URI.parse("https://" + attachment_url)
    Net::HTTP.start(uri.host, uri.port,
      :use_ssl => uri.scheme == 'https',
      :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|
      request = Net::HTTP::Get.new uri.request_uri
      request.basic_auth(ENV['FILEMAKER_ACCOUNT_NAME'], ENV['FILEMAKER_PASSWORD'])
      response = http.request request # Net::HTTPResponse object
      send_data(response.body, :filename => "filename.zip", :type => "application/zip, application/octet-stream")
    end
`
Have a create weekend!

Andreas

**Comment by mech** [comment]
Yup you 2 :)
